version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: true 

python:
  install:
    - method: pip
      path: .
      extra_requirements: [docs]

formats:
  - pdf
  - epub

build:
  jobs:
    post_install:
      - pip install mkdocs-material mkdocs-redirects
